name: CI

on:
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: {% raw %}${{ github.workflow }}-${{ github.ref }}
  {% endraw %}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: true

      - uses: actions/setup-python@v7
        with:
          python-version: "{{ python_version }}"

      - uses: extractions/setup-just@v4

      - name: Install dependencies
        run: just ci-install

      - name: Run linting
        run: just check

      - name: Run tests
        run: just test
